version: "3.8"

services:
  gui:
    build: ./app
    container_name: felix-app
    volumes:
        # mount the app directory - except node_modules - into the container
        # this ensures node_modules is not overwritten on the container
        - ./app:/app:delegated
        - /app/node_modules
    ports:
        - "3000:3000" # maps host port to container port

  server:
      build: ./server
      container_name: felix-net
      volumes:
          - ./server:/felix/server # mount the server directory into the container
      ports:
          - "5000:5000" # maps host port to container port