version: "3.8"

services:
  gui:
    build: ./app
    container_name: felix-app
    volumes:
        - ./app:/app # mount the app directory into the container
    ports:
        - "3000:3000" # maps host port to container port

  server:
      build: ./app
      container_name: felix-net
      volumes:
          - ./server:/server # mount the server directory into the container
      ports:
          - "5000:5000" # maps host port to container port